version: '3'

services:
  app:
    image: kanboard/kanboard
    volumes:
     - /var/data/kanboard/data:/var/www/app/data
     - /var/data/kanboard/plugins:/var/www/app/plugins
    networks:
    - internal

  proxy:
    image: a5huynh/oauth2_proxy
    env_file : /var/data/config/kanboard/kanboard.env
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:kanboard.funkypenguin.co.nz
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /var/data/config/kanboard/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://app
      -redirect-url=https://kanboard.funkypenguin.co.nz
      -http-address=http://0.0.0.0:4180
      -email-domain=funkypenguin.co.nz
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt

#  cron:
#    image: kanboard/kanboard
#    volumes:
#     - /var/data/kanboard/data:/var/www/app/data
#    user: nginx
#    networks:
#      - internal
#    entrypoint: |
#      bash -c 'bash -s <<EOF
#        trap "break;exit" SIGHUP SIGINT SIGTERM
#        while [ ! -f /var/www/app/config.php ]; do
#          sleep 1
#        done
#        while true; do
#          cd /var/www/app
#          ./cli cron
#          sleep 8h
#        done
#      EOF'

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.8.0/24
