- name: add ubuntu docker apt-key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg 
    state: present 

- name: install ubuntu docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: install docker packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - python3-docker

- name: init the swarm on the first node
  docker_swarm:
    state: present
  register: docker_swarm_init
  notify: Set the join tokens as an Ansible fact
  delegate_to: "{{ play_hosts[0] }}"

- set_fact:
    # worker_token:   "{{ docker_swarm_init.swarm_facts.JoinTokens.Worker }}"
    manager_token:  "{{ docker_swarm_init.swarm_facts.JoinTokens.Manager }}"
    master_ip:      "{{ hostvars[play_hosts[0]].ansible_default_ipv4.address }}"

- name: join the swarm on the remaining nodes
  docker_swarm:
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    remote_addrs: "{{ master_ip }}"
    join_token: "{{ manager_token }}"
    state: join
  when: inventory_hostname != play_hosts[0]