- name: add ubuntu docker apt-key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg 
    state: present 

- name: install ubuntu docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install docker packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli

- name: determine swarm status
  shell: >
    docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: swarm_status

- name: create swarm_manager_operational group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_manager_operational
  with_items: "{{ ansible_play_hosts | default(play_hosts) }}"
  when: "'active' in hostvars[item].swarm_status.stdout_lines"
  run_once: true

- name: create swarm_manager_bootstrap group
  add_host:
    hostname: "{{ item }}"
    groups: swarm_manager_bootstrap
  with_items: "{{ ansible_play_hosts | default(play_hosts) }}"
  when: "'active' not in hostvars[item].swarm_status.stdout_lines"
  run_once: true


