apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: unifi
  name: controller
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - image: funkypenguin/oauth2_proxy
          name: controller
          command:
      args: |
      - -upstream=https://controller:8443
      - -ssl-insecure-skip-verify=true
      - -redirect-url=https://unifi.funkypenguin.co.nz
      - -http-address=http://0.0.0.0:4180
      - -email-domain=funkypenguin.co.nz
      - -provider=github
      - -authenticated-emails-file=/authenticated-emails.txt
      - -ssl-insecure-skip-verify
#          resources:
# populate these after doing some measurements
#            requests:
#              memory: "10Mi"
#              cpu: "0.01"
#            limits:
#              memory: "50Mi"
#              cpu: "0.02"
        volumeMounts:
          - name: authenticated-emails.txt
            mountPath: /authenticated-emails.txt
      volumes:
        - name: authenticated-emails.txt
          configMap:
            name: authenticated-emails.txt
