version: "3.0"

services:
  plex:
    image: linuxserver/plex
    env_file: /var/data/config/plex/plex.env
    volumes:
      - /srv/ssd-data/htpc/plex:/config
      - /srv/data/:/data
    deploy:
      labels:
        - traefik.frontend.rule=Host:plex.funkypenguin.co.nz
        - traefik.docker.network=traefik_public
        - traefik.port=32400
    networks:
        - traefik_public
        - internal
    ports:
      - 32469:32469
      - 32400:32400
      - 32401:32401
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  plexpy:
    image: linuxserver/plexpy:latest
    volumes:
     - /var/data/media/:/media
     - /var/data/autopirate/plexpy:/config
    networks:
    - internal

  plexpy_proxy:
    image: zappi/oauth2_proxy
    env_file : /var/data/config/plex/plexpy.env
    dns_search: myswarm.example.com
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:plexpy.funkypenguin.co.nz
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /var/data/config/plex/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://plexpy:8181
      -redirect-url=https://plexpy.funkypenguin.co.nz
      -http-address=http://0.0.0.0:4180
      -email-domain=example.com
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.16.0/24
