names:                          # Name everything!
  deployment: Huginn            # The name of the deployment
  service: Huginn               # The name of the service

app:
  replicas: 1                   # The number of pods this app should start and maintain
  labels:                       # Labels are customizable to how you like.
    app: Huginn                 # App is the only required label

  resources: {}                 # Set the resources you want to allocate to each pod

  image:
    image: huginn/huginn        # The image to use for this deployment, changing it is not recommended.
    pullPolicy: IfNotPresent    # The Image Pull Policy (The same one if you were writing it yourself!)

  service:                      
    internalPort: 3000          # The port the service exposes on the deployment

  probes:
    liveness:
      httpPath: /               # An HTTP path on the container that will return something if it is all live and healthy
    readiness:
      httpPath: /               # An HTTP path on the container that will return something when the container is classified as "Ready"

ingress:
  enabled: true                 # Enabled Ingress for this deployment
  type: traefik                 # Either `traefik` or `kube`, Defines the type of ingress rule to use
  host: huginn.local            # The host you can access this service at
  path: /                       # A path you can access it at, It is not recommended to change it off `/`



    