# This file defines the config for "ct" (chart tester) used by the helm linting GitHub workflow

# Here we define every possible upstream repo our charts use in `requirements.yaml`
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - stable=https://kubernetes-charts.storage.googleapis.com/
  - fairwinds=https://charts.fairwinds.com/stable
  - jetstack=https://charts.jetstack.io
  - loki=https://grafana.github.io/loki/charts
  - kube-eagle=https://raw.githubusercontent.com/cloudworkz/kube-eagle-helm-chart/master

lint-conf: .ci/lint-config.yaml
chart-yaml-schema: .ci/chart_schema.yaml

excluded-charts:
  - funkycore
  - wash-hands

check-version-increment: false
