# This file defines the config for "ct" (chart tester) used by the helm linting GitHub workflow

# Here we define every possible upstream repo our charts use in `requirements.yaml`
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - stable=https://kubernetes-charts.storage.googleapis.com/
  - fairwinds=https://charts.fairwinds.com/stable
  - jetstack=https://charts.jetstack.io
  - loki=https://grafana.github.io/loki/charts
  - kube-eagle=https://raw.githubusercontent.com/cloudworkz/kube-eagle-helm-chart/master
  - premix=https://raw.githubusercontent.com/funkypenguin/geek-cookbook-premix/helm-charts/?token=${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}

lint-conf: .ci/lint-config.yaml
excluded-charts:
  - funkycore
