

# This instructs AKS to assign an _internal_ loadbalancer IP to the service
# nginx-ingress:
#   controller:
#     service:
# #      loadBalancerIP: set-this-if-you-have-a-static-lb-ip

goldilocks:

  installVPA: true
  uninstallVPA: false
  reinstallVPA: false
  vpaVersion: e16a0adef6c7d79a23d57f9bbbef26fc9da59378

  controller:
    flags:
      on-by-default: true

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: this.isnt.working.yet
        paths:
        - /

certmanager:
  letsencrypt:
    email: your@email.here
    dns01:
      cloudflare:
        enabled: true
        email: your@email.here
        api_token: your-api-token-here