version: '3'

services:
    db:
      image: postgres:latest
      env_file: /var/data/ttrss/ttrss.env
      volumes:
        - /var/data/ttrss/database:/var/lib/postgresql/data
      networks:
        - internal

    app:
      image: funkypenguin/docker-ttrss
      env_file: /var/data/ttrss/ttrss.env
      deploy:
        labels:
          - traefik.frontend.rule=Host:ttrss.funkypenguin.co.nz
          - traefik.docker.network=traefik
          - traefik.port=8080
      networks:
        - internal
        - traefik

    db-backup:
      image: postgres:latest
      env_file: /var/data/ttrss/ttrss.env
      volumes:
        - /var/data/ttrss/database-dump:/dump
      entrypoint: |
        bash -c 'bash -s <<EOF
        trap "break;exit" SIGHUP SIGINT SIGTERM
        sleep 2m
        while /bin/true; do
          pg_dump -Fc > /dump/dump_`date +%d-%m-%Y"_"%H_%M_%S`.psql
          sleep $$BACKUP_FREQUENCY
        done
        EOF'
      networks:
      - internal

networks:
  traefik:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.4.0/24
