version: '3'
services:
  db:
    image: mattermost/mattermost-prod-db
    networks:
      - internal
    volumes:
      # use a named-volume for data persistency
      - /var/data/runtime/mattermost/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
      # uncomment the following to enable backup
      # - AWS_ACCESS_KEY_ID=XXXX
      # - AWS_SECRET_ACCESS_KEY=XXXX
      # - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
      # - AWS_REGION=us-east-1

  app:
    image: mattermost/mattermost-prod-app
    networks:
      - internal
      - traefik_public
    volumes:
      - /var/data/mattermost/config:/mattermost/config:rw
      - /var/data/mattermost/data:/mattermost/data:rw
      - /var/data/mattermost/logs:/mattermost/logs:rw
      - /var/data/mattermost/plugins/plugins:/mattermost/plugins:rw
      - /var/data/mattermost/plugins/client:/mattermost/client/plugins:rw      
      - /etc/localtime:/etc/localtime:ro
    env_file: /var/data/config/mattermost/mattermost.env
    deploy:
      labels:
        - traefik.docker.network=traefik_public
        - traefik.frontend.rule=Host:mattermost.funkypenguin.co.nz
        - traefik.port=8000

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.40.0/24
