version: '3.3'
services:
  db:
    # use official mattermost prod-db image
    image: mattermost/mattermost-prod-db
    networks:
      - internal
    volumes:
      # use a named-volume for data persistency
      - /share/runtime/mattermost/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
      # uncomment the following to enable backup
      # - AWS_ACCESS_KEY_ID=XXXX
      # - AWS_SECRET_ACCESS_KEY=XXXX
      # - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
      # - AWS_REGION=us-east-1
    deploy:
      restart_policy:
        condition: on-failure

  app:
    # use official mattermost prod-app image
    image: mattermost/mattermost-prod-app
    networks:
      - internal
      - traefik_public
    volumes:
      - /share/appdata/mattermost/config:/mattermost/config:rw
      - /share/appdata/mattermost/data:/mattermost/data:rw
      - /share/appdata/mattermost/logs:/mattermost/logs:rw
      - /share/appdata/mattermost/plugins/plugins:/mattermost/plugins:rw
      - /share/appdata/mattermost/plugins/client:/mattermost/client/plugins:rw      
      - /etc/localtime:/etc/localtime:ro
    environment:
      # use service's hostname
      - DB_HOST=db
      # talk to the port within the overlay network
      # without (over)exposing ports
      - DB_PORT_NUMBER=5432
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # pass the edition to be used, default is enterprise
      # setting this env var will make the app use the team edition
      - edition=team
      # in case your config is not in default location
      # - MM_CONFIG=/mattermost/config/config.json
    deploy:
      labels:
        - traefik.docker.network=traefik_public
        - traefik.frontend.rule=Host:mattermost.gkoerk.com
        - traefik.port=8000
      restart_policy:
        condition: on-failure

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.179.0/24