version: '3'

services:
  dex:
    image: mdbraber/dex 
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - /var/data/dex/config/config.yml:/config.yml
      - /var/data/dex/db:/db
    networks:
      - traefik_public
    command: ['serve','/config.yml']
    deploy:
      labels:
        - traefik.frontend.rule=Host:dexhq.funkypenguin.co.nz
        - traefik.port=5556
        - traefik.docker.network=traefik_public

networks:
  traefik_public:
    external: true
