---
# tasks file for k3s-master

- name: install k3s on master without agent
  shell: >
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--no-deploy traefik
    --kube-apiserver-arg enable-admission-plugins=PodSecurityPolicy,NodeRestriction" sh -
  args:
    creates: /usr/local/bin/k3s
    warn: no
  register: master_install_result

- name: results of installation
  debug: var=master_install_result.stdout_lines
  when: 
  - master_install_result is changed

- name: fetch k3s.yaml
  become: yes
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig }}"
    flat: yes

- name: update master ip in k3s.yaml
  replace:
    path: "{{ kubeconfig }}"
    regexp: '127.0.0.1'
    replace: "{{ hostvars[groups['k3s_masters'][0]].ansible_default_ipv4.address }}"
  delegate_to: localhost

- name: update cluster name k3s.yaml
  replace:
    path: "{{ kubeconfig }}"
    regexp: 'default'
    replace: "{{ cluster_name }}"
  delegate_to: localhost
