name: CI

on:
  push:
    branches:
      - master
    paths:
      - charts/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish helm charts
      uses: J12934/helm-gh-pages-action@v1.1.0
      with:
        # A personal access token needed to push your site after it has been built.
        access-token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        # The branch expected by GitHub to have the static files needed for your site.
        deploy-branch: helm-charts
        # The folder in which the helm charts are located
        charts-folder: charts
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new helm chart, at {{ EVENT_PAYLOAD.repository.full_name }} has been deployed/updated'