name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Helm Publish
      uses: J12934/helm-gh-pages-action@v1.1.0
      with:
        # A personal access token needed to push your site after it has been built.
        access-token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        # The branch expected by GitHub to have the static files needed for your site.
        deploy-branch: helm-charts
        # The folder in which the helm charts are located
        charts-folder: charts
