name: Publish helm chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
      id: installhelm3
      with:
        version: 'v3.0.3'
    - name: Kubernetes Toolset
      uses: stefanprodan/kube-tools@v1.3.0
      with:
        command: |
          helm3 repo add premix https://${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}@raw.githubusercontent.com/funkypenguin/geek-cookbook-premix/helm-charts/
    - name: Publish helm charts
      uses: funkypenguin/helm-gh-pages-action@v1.1.1
      with:
        # A personal access token needed to push your site after it has been built.
        access-token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        # The branch expected by GitHub to have the static files needed for your site.
        deploy-branch: helm-charts
        # The folder in which the helm charts are located
        charts-folder: charts
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Hey geeks! 🤓 A shiny new/updated helm chart is out of the over, at {{ EVENT_PAYLOAD.repository.full_name }}'
